# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vecmult <- function(x, y) {
    .Call(`_DOPE_vecmult`, x, y)
}

subst <- function(x, row, column_min, column_max) {
    .Call(`_DOPE_subst`, x, row, column_min, column_max)
}

matprod <- function(x) {
    .Call(`_DOPE_matprod`, x)
}

augment_loop <- function(x, n, buff) {
    .Call(`_DOPE_augment_loop`, x, n, buff)
}

